# Basic
title: Eric
subtitle: Temporary is the reality, eternal life is the ideal.
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
welcome_message: <a href="https://github.com/" target="_blank">Download the theme</a>
description: Welcome to Eric0720's blog.
#creator: <a href="http://onev.cat">@onevcat</a>
creator: <a href="http://github.com">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    #- {title: Projects, description: My Projects, url: 'http://www.liujianwei.site'}
     - {title: Project, description: A button, url: 'http://example.com'}


# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: Eric0720
    github: Eric0720
    twitter: Eric1003181417
    gplus: 107108267
    mail: me@liujianwei.site

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
